apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: remove
      image: alpine
      script: |
        echo "Cleaning up workspace"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  steps:
    - name: test
      image: python:3.9
      script: |
        pip install nose
        nosetests
